#include "main.h"

int main(void){
	SystemCoreClockUpdate();
	SysTick_Config(SystemCoreClock / 1000);
	
	RCC->AHB4ENR |= RCC_AHB4ENR_GPIOIEN;
	
	GPIOI->MODER &= ~(GPIO_MODER_MODE12 | GPIO_MODER_MODE13 | GPIO_MODER_MODE14 | GPIO_MODER_MODE15);
	GPIOI->MODER |= (GPIO_MODER_MODE12_0 | GPIO_MODER_MODE13_0 | GPIO_MODER_MODE14_0 | GPIO_MODER_MODE15_0);
	
	RCC->APB4ENR |= RCC_APB4ENR_SYSCFGEN; 
	
	RCC->AHB4ENR |= RCC_AHB4ENR_GPIOCEN;
	GPIOA->MODER &= ~(GPIO_MODER_MODE13);
	
	
	SYSCFG->EXTICR[3] &= ~SYSCFG_EXTICR4_EXTI13; 
  SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PC;
	
	// EXTI->FTSR1 |= EXTI_FTSR1_TR0;
	// EXTI->RTSR1 |= EXTI_RTSR1_TR0; 
	
	// EXTI->D3PMR1 |= EXTI_D3PMR1_MR0; 
	
	NVIC_EnableIRQ(EXTI15_10_IRQn);
	
	
	while(1){
		GPIOI->ODR &= ~GPIO_ODR_OD13;
		delay_ms(500);
		GPIOI->ODR |= GPIO_ODR_OD13;
		delay_ms(500);
	}
	
}

